#!/bin/bash
echo "SRBMiner-MULTI --algorithm $ALGO --pool $POOL_ADDRESS --wallet $WALLET_USER --password $PASSWORD $EXTRAS"
./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc620smyrslt6usnfq3xc -m 16 -p rpc -r dero.rabidmining.com:10300 -r1 community-pools.mysrv.cloud:10300
